//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTHD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDH
    {
        public DonDH()
        {
            this.CT_DonDH = new HashSet<CT_DonDH>();
        }
    
        public int Id { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime NgayGiao { get; set; }
        public double TongTien { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string GhiChu { get; set; }
        public int Id_TinhTrang { get; set; }
        public Nullable<int> Id_NguoiDung { get; set; }
        public int TrangThai { get; set; }
    
        public virtual ICollection<CT_DonDH> CT_DonDH { get; set; }
        public virtual TinhTrangDonDH TinhTrangDonDH { get; set; }
    }
}
