//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTHD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int Id { get; set; }
        public string MatKhau { get; set; }
        public int Id_Quyen { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public int KichHoat { get; set; }
        public int TrangThai { get; set; }
    
        public virtual Quyen Quyen { get; set; }
    }
}
