//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTHD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            this.SanPham = new HashSet<SanPham>();
        }
    
        public int Id { get; set; }
        public string TenNhaCC { get; set; }
        public int TrangThai { get; set; }
    
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
