//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTHD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.CT_DonDH = new HashSet<CT_DonDH>();
            this.PhieuNhap = new HashSet<PhieuNhap>();
            this.TonKho = new HashSet<TonKho>();
        }
    
        public int Id { get; set; }
        public string TenSP { get; set; }
        public int Id_NCC { get; set; }
        public string HDD { get; set; }
        public string RAM { get; set; }
        public string CPU { get; set; }
        public double DonGia { get; set; }
        public string HinhAnh { get; set; }
        public string BaoHanh { get; set; }
        public int LuotXem { get; set; }
        public int SoLuong { get; set; }
        public int TrangThai { get; set; }
    
        public virtual ICollection<CT_DonDH> CT_DonDH { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual ICollection<PhieuNhap> PhieuNhap { get; set; }
        public virtual ICollection<TonKho> TonKho { get; set; }
    }
}
