//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTHD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTrangDonDH
    {
        public TinhTrangDonDH()
        {
            this.DonDH = new HashSet<DonDH>();
        }
    
        public int Id { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual ICollection<DonDH> DonDH { get; set; }
    }
}
